dirs = client stompl broker

clean:
	cd stompl; make clean 
	cd client; make clean
	cd broker; make clean

dist-clean:
	cd stompl; make dist-clean 
	cd client; make dist-clean 
	cd broker; make dist-clean 
